AWSTemplateFormatVersion: "2010-09-09"
Description: Minecraftサーバーを構築するCloudFormationテンプレート

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: minecraft-server-vpc

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: minecraft-server-igw

  VPCGatewayAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  PubSub:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/16

  PubSubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: minecraft-server-rt

  PubSubToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PubSubRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  AssoPubSubRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSub
      RouteTableId: !Ref PubSubRT

  EC2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0ad215c298e692194
      InstanceType: t4g.small
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref PubSub
          GroupSet:
            - !Ref EC2SG
      UserData: !Base64 |
        #!/bin/bash
        # *** INSERT SERVER DOWNLOAD URL BELOW ***
        # Do not add any spaces between your link and the "=", otherwise it won't work. EG: MINECRAFTSERVERURL=https://urlexample


        MINECRAFTSERVERURL=https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar


        # Download Java
        sudo yum install -y java-17-amazon-corretto-headless
        # Install MC Java server in a directory we create
        adduser minecraft
        mkdir /opt/minecraft/
        mkdir /opt/minecraft/server/
        cd /opt/minecraft/server

        # Download server jar file from Minecraft official website
        wget $MINECRAFTSERVERURL

        # Generate Minecraft server files and create script
        chown -R minecraft:minecraft /opt/minecraft/
        java -Xmx1300M -Xms1300M -jar server.jar nogui
        sleep 40
        sed -i 's/false/true/p' eula.txt
        touch start
        printf '#!/bin/bash\njava -Xmx1300M -Xms1300M -jar server.jar nogui\n' >> start
        chmod +x start
        sleep 1
        touch stop
        printf '#!/bin/bash\nkill -9 $(ps -ef | pgrep -f "java")' >> stop
        chmod +x stop
        sleep 1

        # Create SystemD Script to run Minecraft server jar on reboot
        cd /etc/systemd/system/
        touch minecraft.service
        printf '[Unit]\nDescription=Minecraft Server on start up\nWants=network-online.target\n[Service]\nUser=minecraft\nWorkingDirectory=/opt/minecraft/server\nExecStart=/opt/minecraft/server/start\nStandardInput=null\n[Install]\nWantedBy=multi-user.target' >> minecraft.service
        sudo systemctl daemon-reload
        sudo systemctl enable minecraft.service
        sudo systemctl start minecraft.service
      Tags:
        - Key: Name
          Value: minecraft-server-instance

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ec2-sg-cf
      GroupDescription: Allow SSH and HTTP access only MyIP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 25565
          ToPort: 25565
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: minecraft-server-sg